image: mukeshsolanki/android:latest

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
   - .gradle/

stages:
  - build
  - test

build:
  stage: build
  script:
  - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/apk/app-debug.apk

unitTests:
  stage: test
  script:
    - ./gradlew test
